# Generated by Django 3.2.9 on 2021-11-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, verbose_name='Article')),
                ('nb_apparitions', models.IntegerField(verbose_name="Nombre d'apparitions")),
                ('moyenne_vus', models.FloatField(verbose_name='Moyenne du nombre de vus')),
                ('notes', models.CharField(max_length=255, verbose_name='Notes/about')),
                ('classe', models.CharField(max_length=255, verbose_name='Class')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
