# Generated by Django 3.2.9 on 2021-11-19 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20211117_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='favoris',
            field=models.ManyToManyField(blank=True, default=None, related_name='favoris', to=settings.AUTH_USER_MODEL),
        ),
    ]
